<?php
class SettingsDataCube
{
	public $properties = array(
		array("prefixedName" => "qb:DataSet", "localName" => "DataSet", "uri" => "http://purl.org/linked-data/cube#", "type" => ""),
		array("prefixedName" => "qb:Observation", "localName" => "Observation", "uri" => "http://purl.org/linked-data/cube#", "type" => ""),
		array("prefixedName" => "qb:dataSet", "localName" => "dataSet", "uri" => "http://purl.org/linked-data/cube#", "type" => ""),
		array("prefixedName" => "qb:ObservationGroup", "localName" => "ObservationGroup", "uri" => "http://purl.org/linked-data/cube#", "type" => ""),
		array("prefixedName" => "qb:observationGroup", "localName" => "observationGroup", "uri" => "http://purl.org/linked-data/cube#", "type" => ""),
		array("prefixedName" => "qb:Attachable", "localName" => "Attachable", "uri" => "http://purl.org/linked-data/cube#", "type" => ""),
		array("prefixedName" => "qb:ComponentProperty", "localName" => "ComponentProperty", "uri" => "http://purl.org/linked-data/cube#", "type" => ""),
		array("prefixedName" => "qb:DimensionProperty", "localName" => "DimensionProperty", "uri" => "http://purl.org/linked-data/cube#", "type" => ""),
		array("prefixedName" => "qb:AttributeProperty", "localName" => "AttributeProperty", "uri" => "http://purl.org/linked-data/cube#", "type" => ""),
		array("prefixedName" => "qb:MeasureProperty", "localName" => "MeasureProperty", "uri" => "http://purl.org/linked-data/cube#", "type" => ""),
		array("prefixedName" => "qb:CodedProperty", "localName" => "CodedProperty", "uri" => "http://purl.org/linked-data/cube#", "type" => ""),
		array("prefixedName" => "qb:concept", "localName" => "concept", "uri" => "http://purl.org/linked-data/cube#", "type" => ""),
		array("prefixedName" => "qb:HierarchicalCodeList", "localName" => "HierarchicalCodeList", "uri" => "http://purl.org/linked-data/cube#", "type" => ""),
		array("prefixedName" => "qb:hierarchyRoot", "localName" => "hierarchyRoot", "uri" => "http://purl.org/linked-data/cube#", "type" => ""),
		array("prefixedName" => "qb:parentChildProperty", "localName" => "parentChildProperty", "uri" => "http://purl.org/linked-data/cube#", "type" => ""),
		array("prefixedName" => "qb:AggregatableHierarchy", "localName" => "AggregatableHierarchy", "uri" => "http://purl.org/linked-data/cube#", "type" => ""),
		array("prefixedName" => "rdf:type", "localName" => "type", "uri" => "http://www.w3.org/1999/02/22-rdf-syntax-ns#", "type" => ""),
		array("prefixedName" => "rdf:first", "localName" => "first", "uri" => "http://www.w3.org/1999/02/22-rdf-syntax-ns#", "type" => ""),
		array("prefixedName" => "rdf:rest", "localName" => "rest", "uri" => "http://www.w3.org/1999/02/22-rdf-syntax-ns#", "type" => ""),
		array("prefixedName" => "rdf:value", "localName" => "value", "uri" => "http://www.w3.org/1999/02/22-rdf-syntax-ns#", "type" => ""),
		array("prefixedName" => "rdf:subject", "localName" => "subject", "uri" => "http://www.w3.org/1999/02/22-rdf-syntax-ns#", "type" => ""),
		array("prefixedName" => "rdf:predicate", "localName" => "predicate", "uri" => "http://www.w3.org/1999/02/22-rdf-syntax-ns#", "type" => ""),
		array("prefixedName" => "rdf:object", "localName" => "object", "uri" => "http://www.w3.org/1999/02/22-rdf-syntax-ns#", "type" => ""),
		array("prefixedName" => "rdfs:subClassOf", "localName" => "subClassOf", "uri" => "http://www.w3.org/2000/01/rdf-schema#", "type" => ""),
		array("prefixedName" => "rdfs:subPropertyOf", "localName" => "subPropertyOf", "uri" => "http://www.w3.org/2000/01/rdf-schema#", "type" => ""),
		array("prefixedName" => "rdfs:domain", "localName" => "domain", "uri" => "http://www.w3.org/2000/01/rdf-schema#", "type" => ""),
		array("prefixedName" => "rdfs:range", "localName" => "range", "uri" => "http://www.w3.org/2000/01/rdf-schema#", "type" => ""),
		array("prefixedName" => "rdfs:label", "localName" => "label", "uri" => "http://www.w3.org/2000/01/rdf-schema#", "type" => ""),
		array("prefixedName" => "rdfs:comment", "localName" => "comment", "uri" => "http://www.w3.org/2000/01/rdf-schema#", "type" => ""),
		array("prefixedName" => "rdfs:member", "localName" => "member", "uri" => "http://www.w3.org/2000/01/rdf-schema#", "type" => ""),
		array("prefixedName" => "rdfs:seeAlso", "localName" => "seeAlso", "uri" => "http://www.w3.org/2000/01/rdf-schema#", "type" => ""),
		array("prefixedName" => "rdfs:isDefinedBy", "localName" => "isDefinedBy", "uri" => "http://www.w3.org/2000/01/rdf-schema#", "type" => ""),
		array("prefixedName" => "dc:contributor", "localName" => "contributor", "uri" => "http://purl.org/dc/elements/1.1/", "type" => ""),
		array("prefixedName" => "dc:coverage", "localName" => "coverage", "uri" => "http://purl.org/dc/elements/1.1/", "type" => ""),
		array("prefixedName" => "dc:creator", "localName" => "creator", "uri" => "http://purl.org/dc/elements/1.1/", "type" => ""),
		array("prefixedName" => "dc:date", "localName" => "date", "uri" => "http://purl.org/dc/elements/1.1/", "type" => ""),
		array("prefixedName" => "dc:description", "localName" => "description", "uri" => "http://purl.org/dc/elements/1.1/", "type" => ""),
		array("prefixedName" => "dc:format", "localName" => "format", "uri" => "http://purl.org/dc/elements/1.1/", "type" => ""),
		array("prefixedName" => "dc:identifier", "localName" => "identifier", "uri" => "http://purl.org/dc/elements/1.1/", "type" => ""),
		array("prefixedName" => "dc:language", "localName" => "language", "uri" => "http://purl.org/dc/elements/1.1/", "type" => ""),
		array("prefixedName" => "dc:publisher", "localName" => "publisher", "uri" => "http://purl.org/dc/elements/1.1/", "type" => ""),
		array("prefixedName" => "dc:relation", "localName" => "relation", "uri" => "http://purl.org/dc/elements/1.1/", "type" => ""),
		array("prefixedName" => "dc:rights", "localName" => "rights", "uri" => "http://purl.org/dc/elements/1.1/", "type" => ""),
		array("prefixedName" => "dc:source", "localName" => "source", "uri" => "http://purl.org/dc/elements/1.1/", "type" => ""),
		array("prefixedName" => "dc:subject", "localName" => "subject", "uri" => "http://purl.org/dc/elements/1.1/", "type" => ""),
		array("prefixedName" => "dc:title", "localName" => "title", "uri" => "http://purl.org/dc/elements/1.1/", "type" => ""),
		array("prefixedName" => "dc:type", "localName" => "type", "uri" => "http://purl.org/dc/elements/1.1/", "type" => "")
	);		
}
?>